- name: Install nginx & exporter
  apt:
    name:
      - nginx
      - prometheus-nginx-exporter
    state: present

- name: Create nginx TLS directory
  file:
    path: /etc/nginx/tls
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Deploy TLS certificate
  copy:
    src: apps.crt
    dest: /etc/nginx/tls/apps.crt
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Deploy TLS key
  copy:
    content: '{{ nginx_tls_key }}'
    dest: /etc/nginx/tls/apps.key
    owner: root
    group: root
    mode: '0600'
  no_log: true
  notify: Restart nginx

- name: Deploy nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: true

- name: Call handlers
  meta: flush_handlers

- name: Start nginx & exporter
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
