- name: Install nginx & exporter
  apt:
    name:
      - nginx
      - prometheus-nginx-exporter
    state: present

- name: Deploy nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: true

- name: Call handlers
  meta: flush_handlers

- name: Start nginx & exporter
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
