- name: Configure sandbox
  hosts: linux01
  become: true
  gather_facts: true
  
  roles:
    - role: common
      tags: [com]

    - role: domain
      tags: [dom]

    - role: samba
      tags: [sam]

    - role: kerberos
      tags: [ker]

    - role: docker
      tags: [doc]

    - role: gitea
      tags: [git]

    - role: keycloak
      tags: [key]

    - role: nginx
      tags: [ng]

    - role: bind
      tags: [bin]

    - role: node_exporter
      tags: [ne]

    - role: prometheus
      tags: [pr]

    - role: grafana
      tags: [gr]