- name: Configure sandbox
  hosts: test01
  become: true
  gather_facts: true
  
  roles:
    - role: common
      tags: [c]

    - role: storage
      tags: [st]

    - role: kerberos
      tags: [k]

    - role: domain
      tags: [d]

    - role: samba
      tags: [smb]
