- name: Configure sandbox
  hosts: test01
  become: true
  gather_facts: true
  
  roles:
    - role: common
      tags: [c]

    - role: storage
      tags: [st]

    - role: kerberos
      tags: [ker]

    - role: domain
      tags: [dom]

    - role: samba
      tags: [sam]

    - role: docker
      tags: [doc]

    - role: gitea
      tags: [git]

    - role: nginx
      tags: [ng]

    - role: bind
      tags: [bind]