- name: Create company groups
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ company_directories }}"

- name: Create company directories
  file:
    path: "/company/{{ item.name }}"
    state: directory
    owner: root
    mode: "{{ item.mode }}"
  loop: "{{ company_directories }}"
