- name: Create company groups
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ company_directories }}"

- name: Create company directories
  file:
    path: "/company/{{ item.name }}"
    state: directory
    owner: root
    mode: "{{ item.mode }}"
  loop: "{{ company_directories }}"

- name: Configure ACLs
  acl:
    path: "{{ item.path }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    state: present
  loop: "{{ company_acls }}"
